// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-members.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_members_default = defineTool({
  name: "list_members",
  title: "List members",
  description: "List members visible to the signed-in user. Supports optional search and status filters.",
  inputSchema: {
    search: z.string().optional().describe("Case-insensitive substring match on first or last name."),
    status: z.enum(["active", "inactive"]).optional().describe("Filter by member status."),
    limit: z.number().int().min(1).max(200).optional().describe("Max number of members to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("members").select("id, first_name, last_name, gender, date_of_birth, status, attendance_count, type").order("last_name", { ascending: true }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (search) q = q.or(`first_name.ilike.%${search}%,last_name.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { members: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-member.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_member_default = defineTool2({
  name: "get_member",
  title: "Get member",
  description: "Fetch full details for a single member by ID.",
  inputSchema: {
    member_id: z2.string().uuid().describe("The member's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ member_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("members").select("*").eq("id", member_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Member not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { member: data }
    };
  }
});

// src/lib/mcp/tools/list-attendance.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_attendance_default = defineTool3({
  name: "list_attendance",
  title: "List attendance records",
  description: "List attendance records within an optional date range. Dates are ISO YYYY-MM-DD.",
  inputSchema: {
    from: z3.string().optional().describe("Start date (inclusive), ISO YYYY-MM-DD."),
    to: z3.string().optional().describe("End date (inclusive), ISO YYYY-MM-DD."),
    member_id: z3.string().uuid().optional().describe("Filter to a single member."),
    limit: z3.number().int().min(1).max(500).optional().describe("Max records (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, member_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("attendance_records").select("id, member_id, event_date, created_at").order("event_date", { ascending: false }).limit(limit ?? 100);
    if (from) q = q.gte("event_date", from);
    if (to) q = q.lte("event_date", to);
    if (member_id) q = q.eq("member_id", member_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { records: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/check-in-member.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var check_in_member_default = defineTool4({
  name: "check_in_member",
  title: "Check in member",
  description: "Record an attendance for a member on a given event date (defaults to today).",
  inputSchema: {
    member_id: z4.string().uuid().describe("The member to check in."),
    event_date: z4.string().optional().describe("Event date ISO YYYY-MM-DD (defaults to today).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ member_id, event_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const date = event_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("attendance_records").insert({ member_id, event_date: date }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Checked in member ${member_id} on ${date}` }],
      structuredContent: { record: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pvdcfvwvmeypelenfzvc";
var mcp_default = defineMcp({
  name: "youth-checkin-mcp",
  title: "Youth Check-In MCP",
  version: "0.1.0",
  instructions: "Tools for the Youth Check-In app. Use list_members to search members, get_member for details, list_attendance to view attendance history, and check_in_member to record attendance. All actions run as the signed-in admin and are enforced by row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_members_default, get_member_default, list_attendance_default, check_in_member_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
